language: rust
cache: cargo

branches:
  only:
  - develop

rust:
- stable

os:
- linux

install:
- rustup component add rustfmt
- rustup component add clippy
- command -v cargo-audit >/dev/null 2>&1 || cargo install cargo-audit

script:
# lint
- cargo fmt --version
- cargo fmt --all -- --check
- cargo clippy --version
- cargo clippy --all

# build
- cargo build --all

# test
- cargo test --all

# audit
- cargo audit

